//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalRecursosHumanos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleadoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleadoes()
        {
            this.Licencias = new HashSet<Licencias>();
            this.Permisoes = new HashSet<Permisoes>();
            this.Salida_Empleado = new HashSet<Salida_Empleado>();
            this.Vacacions = new HashSet<Vacacions>();
        }
    
        public int Id_Empleado { get; set; }
        public string CodigoEmpleado { get; set; }
        public string Nombre_Empleado { get; set; }
        public string Apellido { get; set; }
        public string Telefono { get; set; }
        public int Id_Depto { get; set; }
        public int Id_Cargo { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public decimal Salario { get; set; }
        public bool status { get; set; }
    
        public virtual Cargoes Cargoes { get; set; }
        public virtual Departamentoes Departamentoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Licencias> Licencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permisoes> Permisoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salida_Empleado> Salida_Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacacions> Vacacions { get; set; }
    }
}
