//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalRecursosHumanos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HumanResourcesEntities2 : DbContext
    {
        public HumanResourcesEntities2()
            : base("name=HumanResourcesEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Cargoes> Cargoes { get; set; }
        public virtual DbSet<Departamentoes> Departamentoes { get; set; }
        public virtual DbSet<Empleadoes> Empleadoes { get; set; }
        public virtual DbSet<Licencias> Licencias { get; set; }
        public virtual DbSet<Nominas> Nominas { get; set; }
        public virtual DbSet<Permisoes> Permisoes { get; set; }
        public virtual DbSet<Salida_Empleado> Salida_Empleado { get; set; }
        public virtual DbSet<Vacacions> Vacacions { get; set; }
    }
}
