//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalRecursosHumanos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nominas
    {
        public int Id_Nomina { get; set; }
        public int Año { get; set; }
        public int Mes { get; set; }
        public decimal Monto_Total { get; set; }
    }
}
